# Generated by Django 5.0.4 on 2024-08-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coupon_name', models.CharField(max_length=100)),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('minimum_amount', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('maximum_amount', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
