# Generated by Django 5.0.4 on 2024-08-31 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='Coupon_name',
            new_name='coupon_name',
        ),
    ]
