# Generated by Django 5.0.4 on 2024-08-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='varient_price',
            new_name='variant_price',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='varient_status',
            new_name='variant_status',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='varient_stock',
            new_name='variant_stock',
        ),
    ]
