# Generated by Django 5.0.4 on 2024-09-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_varient_price_productvariant_variant_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
