# Generated by Django 5.0.4 on 2024-09-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
