# Generated by Django 5.0.4 on 2024-09-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0004_alter_useraddress_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
