# Generated by Django 5.0.4 on 2024-07-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='category_image/default.png', upload_to='category_image/'),
        ),
    ]
